image: ghcr.io/typst/typst:latest

stages:
  - build
  - deploy

variables:
  CV_SOURCE: cv.typ
  OUTPUT_FILE: cv.pdf

compile_cv:
  stage: build
  script:
    - echo "Compiling CV with Typst..."
    # Avoid using colons in echo statements
    - echo "Font files already in repository"
    - ls -la *.otf *.ttf || echo "Font listing for verification"
    - typst compile $CV_SOURCE $OUTPUT_FILE
    - echo "CV compilation complete"
  artifacts:
    paths:
      - $OUTPUT_FILE
    expire_in: 1 week

# Deploy to GitLab Pages if desired
pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp $OUTPUT_FILE public/
    # Avoid using colons in echo statements
    - echo "PDF available at ${CI_PAGES_URL}/${OUTPUT_FILE}"
  artifacts:
    paths:
      - public
  only:
    - main  # Only run on the main branch