image: debian:bullseye-slim

stages:
  - build
  - deploy

variables:
  CV_SOURCE: cv.typ
  OUTPUT_FILE: cv.pdf
  TYPST_VERSION: "v0.13.0"  # Adjust this to your preferred Typst version

compile_cv:
  stage: build
  script:
    # Install minimal dependencies
    - apt-get update && apt-get install -y curl xz-utils fontconfig
    
    # Install Typst
    - curl -L https://github.com/typst/typst/releases/download/${TYPST_VERSION}/typst-x86_64-unknown-linux-musl.tar.xz | tar -xJf - -C /tmp
    - mv /tmp/typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
    - chmod +x /usr/local/bin/typst
    
    # Setup fonts from repository
    - mkdir -p ~/.fonts/
    - cp fonts/* ~/.fonts/ || true
    - fc-cache -f -v
    
    # List available fonts for debugging
    - echo "Available fonts:"
    - fc-list | grep -i "awesome\\|roboto"
    
    # Show Typst version
    - typst --version
    
    # Compile the CV
    - echo "Compiling CV with Typst..."
    - typst compile $CV_SOURCE $OUTPUT_FILE
    - echo "CV compilation complete"
  artifacts:
    paths:
      - $OUTPUT_FILE
    expire_in: 1 week

# Deploy to GitLab Pages
pages:
  stage: deploy
  cache:
    key: pdf-builds
    paths:
      - public/builds
    policy: pull-push
  script:
    - mkdir -p public/builds
    - cp $OUTPUT_FILE public/cv.pdf
    - cp $OUTPUT_FILE public/builds/cv-${CI_COMMIT_SHA:0:8}.pdf
    - echo "Creating dynamic GitLab Pages interface..."
    
        # Copy the static website files
    - cp index.html public/
    - cp style.css public/
    - cp script.js public/
    - cp config.js public/
    
    - echo "GitLab Pages deployment complete"
  artifacts:
    paths:
      - public
  only:
    - main  # Only run on the main branch 