stages:
  - build

build:
  stage: build
  image: moss/xelatex
  script:
    - apt update
    - apt install -y texlive-fonts-extra fonts-font-awesome
    - bash install_roboto.sh
    - make all
  artifacts:
    paths:
      - artifacts/*/*.pdf