name: build
on: push
jobs:
  pdf:
    runs-on: ubuntu-latest
    container:
      image: blang/latex:ubuntu
      options: --user root
    steps:
      - name: Manual checkout
        run: |
          apt-get update
          apt-get install -y git
          git clone --depth 1 https://github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}

      - run: echo "I'm in $(pwd)"
      - run: ls
      - run: bash install_roboto.sh
      - run: make all

      - name: Store pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf-artifacts
          path: artifacts/*/*.pdf