name: build
on: push
jobs:
  pdf:
    runs-on: ubuntu-latest
    container: blang/latex:ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo "I'm in $(pwd)"
      - run: ls
      - run: bash install_roboto.sh
      - run: make all
      - name: Store pdf artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdf-artifacts
          path: artifacts/*/*.pdf