name: build
on: push
jobs:
  pdf:
    runs-on: ubuntu-latest
    container: moss/xelatex
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: apt update && apt install -y texlive-fonts-extra fonts-font-awesome
      - run: bash install_roboto.sh
      - run: make all
      - name: Store pdf artifact
        uses: actions/upload-artifact@v3
        with:
          name: pdf-artifacts
          path: artifacts/*.pdf
